# azure-pipelines-templates/build-template.yml
parameters:
  - name: buildCommand
    type: string
    default: 'npm run build'

jobs:
  - job: BuildJob
    displayName: 'Build Application'
    steps:
      - script: ${{ parameters.buildCommand }}  # Build the application
        displayName: 'Build the application'
