# azure-pipelines-templates/build-template.yml
parameters:
  - name: buildCommand
    type: string
    default: 'npm run build'

steps:
  - script: |
      /myagent/_work/_tool/node/18.20.4/x64/bin/npm run build  # Use full path to npm
    displayName: 'Build the application'
