# azure-pipelines-templates/deploy-template.yml
parameters:
  - name: deployCommand
    type: string
    default: './deploy.sh'

steps:
  - script: ${{ parameters.deployCommand }}  # Execute the deployment script
    displayName: 'Deploy the application'
