# azure-pipelines-templates/deploy-template.yml
parameters:
  - name: deployCommand
    type: string
    default: './deploy.sh'

jobs:
  - job: DeployJob
    displayName: 'Deploy Application'
    steps:
      - script: ${{ parameters.deployCommand }}  # Execute the deployment script
        displayName: 'Deploy the application'
