# azure-pipelines-templates/npm-install-template.yml
parameters:
  - name: nodeVersion
    type: string
    default: '16.x'
  - name: installCommand
    type: string
    default: 'npm install'

steps:
  - task: NodeTool@0  # Install Node.js
    inputs:
      versionSpec: ${{ parameters.nodeVersion }}  # Specify Node.js version
    displayName: 'Install Node.js'

  - script: |
      npm install -g npm  # Ensure npm is installed globally
      ${{ parameters.installCommand }}  # Install npm dependencies
    displayName: 'Install npm packages'
 - script: |
    echo "Node.js version:"
    node -v
    echo "npm version:"
    npm -v  # Check npm version
    ${{ parameters.installCommand }}  # Install npm dependencies
  displayName: 'Check Node.js and npm versions'
