# azure-pipelines-templates/npm-install-template.yml
parameters:
  - name: nodeVersion
    type: string
    default: '18.x'
  - name: installCommand
    type: string
    default: 'npm install'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ parameters.nodeVersion }}
    displayName: 'Install Node.js'

  - script: |
      echo "Node.js version:"
      node -v
      echo "npm version:"
      npm -v
    displayName: 'Check Node.js and npm version'

  - script: |
      ${{ parameters.installCommand }}  # Install npm dependencies
    displayName: 'Install npm packages'

  - script: |
      /myagent/_work/_tool/node/18.20.4/x64/bin/npm run build  # Use full path to npm
    displayName: 'Build the application'
