parameters:
  nodeVersion: '16.x'
  installCommand: 'npm install'
  testCommand: 'npm test'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: ${{ parameters.nodeVersion }}
  displayName: 'Install Node.js'

- script: |
    ${{ parameters.installCommand }}
  displayName: 'Install npm dependencies'

- script: |
    ${{ parameters.testCommand }}
  displayName: 'Run tests'
