trigger:
  branches:
    include:
      - main

pool:
  name: azure-first project

jobs:
- job: Test
  displayName: 'Test Application'
  strategy:
    matrix:
      node16:
        nodeVersion: '16.x'
      node18:
        nodeVersion: '18.x'
      node20:
        nodeVersion: '20.x'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ matrix.nodeVersion }}
    displayName: 'Install Node.js'

  - script: |
      echo "Node.js version:"
      node -v
      npm install  # Install npm dependencies
    displayName: 'Install npm packages'

  - script: |
      npm run test  # Run your tests
    displayName: 'Run tests'
