trigger:
- main

pool:
  name: azure-first project

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16.x'
  displayName: 'Install Node.js'

# Optionally, create a custom npm cache path via .npmrc
- script: |
    echo "cache=${HOME}/.npm" > .npmrc
  displayName: 'Create .npmrc with custom cache path'

# Restore npm dependencies from cache
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
      npm | "$(Agent.OS)"
    path: $(HOME)/.npm  # Path where npm caches dependencies
  displayName: 'Restore npm cache'

# Install npm dependencies and build the project
- script: |
    npm install
    npm run build || echo "No build script, skipping build step"
  displayName: 'npm install and build'

# Cache npm dependencies after the installation step
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    path: $(HOME)/.npm  # Path where npm caches dependencies
  displayName: 'Cache npm dependencies'
