trigger:
  branches:
    include:
      - main  # Trigger the pipeline on pushes to the main branch

pool:
  name: 'azure-first project'  # Use your specified agent pool

stages:
  - stage: Install  # Stage for installing npm packages
    displayName: 'Install Stage'
    jobs:
      - job: InstallJob  # Job for installing npm packages
        displayName: 'Install npm packages'
        steps:
          - template: azure-pipelines-templates/npm-install-template.yml  # Reference npm install template
            parameters:
              nodeVersion: '18.x'
              installCommand: 'npm install'

