trigger:
- main  # Change this to your main branch

pool:
  name: azure-first project  # Specify the VM image you want to use

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  strategy:
    matrix:
      Node14_MySQL:
        NODE_VERSION: '14'
        DB: 'mysql'
      Node16_Postgres:
        NODE_VERSION: '16'
        DB: 'postgres'
      Node18_SQLite:
        NODE_VERSION: '18'
        DB: 'sqlite'
  steps:
  - script: |
      echo "Testing in Node version $(NODE_VERSION) with $(DB) database"
      # Install dependencies
      npm install
      # Run tests
      npm test
    displayName: 'Run Tests'
