trigger:
- main

pool:
  name: azure-first project

# install steps
- template: azure-pipelines-templates/npm-install-template.yml
  parameters:
    nodeVersion: '16.x'
    installCommand: 'npm install'

# Build steps
- template: azure-pipelines-templates/build-template.yml
  parameters:
    buildCommand: 'npm run build'

# Deploy steps
- template: azure-pipelines-templates/deploy-template.yml
  parameters:
    deployCommand: './deploy.sh'
