trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

# npm install steps
- template: azure-pipelines-templates/npm-install-template.yml
  parameters:
    nodeVersion: '16.x'
    installCommand: 'npm install'

# Run test steps
- template: azure-pipelines-templates/test-template.yml
  parameters:
    testCommand: 'npm run test'

# Build steps
- template: azure-pipelines-templates/build-template.yml
  parameters:
    buildCommand: 'npm run build'

# Deploy steps
- template: azure-pipelines-templates/deploy-template.yml
  parameters:
    deployCommand: './deploy.sh'
