trigger:
  branches:
    include:
      - main  # Trigger the pipeline on pushes to the main branch

pool:
  name: azure-first project  # Use the Ubuntu image for the build agent

stages:
  - stage: Install  # Stage for installing npm packages
    displayName: 'Install Stage'
    jobs:
      - job: InstallJob  # Job for installing npm packages
        displayName: 'Install npm packages'
        steps:
          - template: azure-pipelines-templates/npm-install-template.yml  # Reference npm install template
            parameters:
              nodeVersion: '16.x'
              installCommand: 'npm install'

  - stage: Build  # Stage for building the application
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob  # Job for building the application
        displayName: 'Build Application'
        steps:
          - template: azure-pipelines-templates/build-template.yml  # Reference build template
            parameters:
              buildCommand: 'npm run build'

  - stage: Deploy  # Stage for deploying the application
    displayName: 'Deploy Stage'
    jobs:
      - job: DeployJob  # Job for deployment
        displayName: 'Deploy Application'
        steps:
          - template: azure-pipelines-templates/deploy-template.yml  # Reference deploy template
            parameters:
              deployCommand: './deploy.sh'
