trigger:
- main

pool:
  name: azure-first project

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  strategy:
    matrix:
      Node16_Postgres:
        NODE_VERSION: '14'
        DB: 'postgres'
      Node20_SQLite:
        NODE_VERSION: '20'
        DB: 'sqlite'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(NODE_VERSION)'
    displayName: 'Install Node.js $(NODE_VERSION)'

  - script: |
      echo "Testing in Node version $(NODE_VERSION) with $(DB) database"
      # Install dependencies
      npm install
      # Run tests
      npm test
    displayName: 'Run Tests'