trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

# Run npm install steps
- template: azure-pipelines-templates/npm-steps.yml
  parameters:
    nodeVersion: '16.x'
    installCommand: 'npm install'

# Run build steps
- template: azure-pipelines-templates/build-template.yml
  parameters:
    buildCommand: 'npm run build'

