trigger:
  branches:
    include:
      - main  # Trigger the pipeline on pushes to the main branch

pool:
  name: azure-first project

jobs:
- job: BuildAndTest
  strategy:
    matrix:
      node10:
        node_version: 10
      node12:
        node_version: 12
  pool:
    name: default
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
  - script: npm install
  - script: npm test

